module.exports = {
  ClienteDto: require("./cliente.dto"),
  DepartamentoDto: require("./departamento.dto"),
  DomicilioDto: require("./domicilio.dto"),
  EmpleadoDto: require("./empleado.dto"),
  LocalidadDto: require("./localidad.dto"),
  PersonaDto: require("./persona.dto"),
  RolEmpleadoDto: require("./rol.empleado.dto"),
  RolDto: require("./rol.dto"),
  UsuarioDto: require("./usuario.dto"),
  StockInsumoDto: require("./stock.insumo.dto"),
  CompraInsumoDto: require("./compra.insumo.dto"),
  UnidadMedidaDto: require("./unidad.medida.dto"),
  InsumoDto: require("./insumo.dto"),
  ArticuloInsumoDto: require("./articulo.insumo.dto"),
  ArticuloDto: require("./articulo.dto"),
  HistorialArticuloVentaDto: require("./historial.articulo.venta.dto"),
  CategoriaDto: require("./categoria.dto"),
  DetallePedidoDto: require("./detalle.pedido.dto"),
  PedidoDto: require("./pedido.dto"),
  EstadosPedidoDto: require("./estados.pedido.dto"),
  ConfiguracionDto: require("./configuracion.dto"),
};
