module.exports = {
  ClienteRepository: require("./cliente.repository"),
  DepartamentoRepository: require("./departamento.repository"),
  DomicilioRepository: require("./domicilio.repository"),
  EmpleadoRepository: require("./empleado.repository"),
  LocalidadRepository: require("./localidad.repository"),
  PersonaRepository: require("./persona.repository"),
  RolEmpleadoRepository: require("./rol.empleado.repository"),
  RolRepository: require("./rol.repository"),
  UsuarioRepository: require("./usuario.repository"),
  StockInsumoRepository: require("./stock.insumo.repository"),
  CompraInsumoRepository: require("./compra.insumo.repository"),
  UnidadMedidaRepository: require("./unidad.medida.repository"),
  InsumoRepository: require("./insumo.repository"),
  ArticuloInsumoRepository: require("./articulo.insumo.repository"),
  ArticuloRepository: require("./articulo.repository"),
  HistorialArticuloVentaRepository: require("./historial.articulo.venta.repository"),
  CategoriaRepository: require("./categoria.repository"),
  DetallePedidoRepository: require("./detalle.pedido.repository"),
  PedidoRepository: require("./pedido.repository"),
  EstadosPedidoRepository: require("./estados.pedido.repository"),
  ConfiguracionRepository: require("./configuracion.repository"),
};
