module.exports = {
  ClienteBusiness: require("./cliente.business"),
  DepartamentoBusiness: require("./departamento.business"),
  DomicilioBusiness: require("./domicilio.business"),
  EmpleadoBusiness: require("./empleado.business"),
  LocalidadBusiness: require("./localidad.business"),
  PersonaBusiness: require("./persona.business"),
  RolEmpleadoBusiness: require("./rol.empleado.business"),
  RolBusiness: require("./rol.business"),
  UsuarioBusiness: require("./usuario.business"),
  StockInsumoBusiness: require("./stock.insumo.business"),
  CompraInsumoBusiness: require("./compra.insumo.business"),
  UnidadMedidaBusiness: require("./unidad.medida.business"),
  InsumoBusiness: require("./insumo.business"),
  ArticuloInsumoBusiness: require("./articulo.insumo.business"),
  ArticuloBusiness: require("./articulo.business"),
  HistorialArticuloVentaBusiness: require("./historial.articulo.venta.business"),
  CategoriaBusiness: require("./categoria.business"),
  DetallePedidoBusiness: require("./detalle.pedido.business"),
  PedidoBusiness: require("./pedido.business"),
  EstadosPedidoBusiness: require("./estados.pedido.business"),
  ConfiguracionBusiness: require("./configuracion.business"),
};
