module.exports = {
  ClienteService: require("./cliente.service"),
  DepartamentoService: require("./departamento.service"),
  DomicilioService: require("./domicilio.service"),
  EmpleadoService: require("./empleado.service"),
  LocalidadService: require("./localidad.service"),
  PersonaService: require("./persona.service"),
  RolEmpleadoService: require("./rol.empleado.service"),
  RolService: require("./rol.service"),
  UsuarioService: require("./usuario.service"),
  StockInsumoService: require("./stock.insumo.service"),
  CompraInsumoService: require("./compra.insumo.service"),
  UnidadMedidaService: require("./unidad.medida.service"),
  InsumoService: require("./insumo.service"),
  ArticuloInsumoService: require("./articulo.insumo.service"),
  ArticuloService: require("./articulo.service"),
  HistorialArticuloVentaService: require("./historial.articulo.venta.service"),
  CategoriaService: require("./categoria.service"),
  DetallePedidoService: require("./detalle.pedido.service"),
  PedidoService: require("./pedido.service"),
  EstadosPedidoService: require("./estados.pedido.service"),
  ConfiguracionService: require("./configuracion.service"),
};
