module.exports = {
  ClienteController: require("./cliente.controller"),
  DepartamentoController: require("./departamento.controller"),
  DomicilioController: require("./domicilio.controller"),
  EmpleadoController: require("./empleado.controller"),
  LocalidadController: require("./localidad.controller"),
  PersonaController: require("./persona.controller"),
  RolEmpleadoController: require("./rol.empleado.controller"),
  RolController: require("./rol.controller"),
  UsuarioController: require("./usuario.controller"),
  StockInsumoController: require("./stock.insumo.controller"),
  CompraInsumoController: require("./compra.insumo.controller"),
  UnidadMedidaController: require("./unidad.medida.controller"),
  InsumoController: require("./insumo.controller"),
  ArticuloInsumoController: require("./articulo.insumo.controller"),
  ArticuloController: require("./articulo.controller"),
  HistorialArticuloVentaController: require("./historial.articulo.venta.controller"),
  CategoriaController: require("./categoria.controller"),
  DetallePedidoController: require("./detalle.pedido.controller"),
  PedidoController: require("./pedido.controller"),
  EstadosPedidoController: require("./estados.pedido.controller"),
  ConfiguracionController: require("./configuracion.controller"),
};
