module.exports = {
  Cliente: require("./cliente"),
  Departamento: require("./departamento"),
  Domicilio: require("./domicilio"),
  Empleado: require("./empleado"),
  Localidad: require("./localidad"),
  Persona: require("./persona"),
  RolEmpleado: require("./rol.empleado"),
  Rol: require("./rol"),
  Usuario: require("./usuario"),
  StockInsumo: require("./stock.insumo"),
  CompraInsumo: require("./compra.insumo"),
  UnidadMedida: require("./unidad.medida"),
  Insumo: require("./insumo"),
  ArticuloInsumo: require("./articulo.insumo"),
  Articulo: require("./articulo"),
  HistorialArticuloVenta: require("./historial.articulo.venta"),
  Categoria: require("./categoria"),
  DetallePedido: require("./detalle.pedido"),
  Pedido: require("./pedido"),
  EstadosPedido: require("./estados.pedido"),
  Configuracion: require("./configuracion"),
};
